project:
  type: website

website:
  title: "Historic Global Surface Temperatures: An Analysis"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-S24/project-01-GraphCrafters
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
